# Generated by Django 2.2.3 on 2019-07-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('precio', models.CharField(max_length=100, verbose_name='Precio')),
                ('guia', models.CharField(max_length=100, verbose_name='Guia')),
                ('fechaPartida', models.CharField(max_length=100, verbose_name='FechaPartida')),
            ],
        ),
    ]
