# Generated by Django 2.2.3 on 2019-07-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
    ]
