# Generated by Django 2.2.2 on 2019-07-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direccion', models.TextField(max_length=200, verbose_name='Direccion')),
                ('ci', models.PositiveIntegerField(verbose_name='CI')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
            ],
        ),
    ]
